### ISSUE TITLE
TrueOS-Desktop-12.0-CURRENT-08-02-2016-x64-USB.img fails to start installer in usable state on Lenovo Thinkpad x260

### ISSUE THREAD

**Issue by duck** [trueos/trueos-desktop#1]
Three attempts all failed to bring the installer up in a usable fashion.
  * CPU: Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
  * 8 G RAM
  * Lenovo Laptop dock

Try 1:
  * Docked, auto select video
  * Result: 
    * No display on dock monitor during entire process, only on the internal panel
    * Fails to start X, seems to lock machine. Had to hard power-cycle machine

Try 2:
  * Docked, select VGA video
  * Result: 
    * No display on dock monitor during boot and menu process, only on the internal panel
    * X starts, shifted way up on screen, resolution all whacked.  Unable to see small dialog windows

Try 3:
  * Undocked, select VGA video
  * Result: 
    * X starts in proper resolution, but never gets past the TrueOS slash screen

I am willing to do more testing as needed to capture logging/etc.

**Comment by pkgdemon** [comment]
Are you able to attach a picture of the splash screen you are referring to?  Can you also try the SCFB, and VESA methods to see if that gets you further?

**Comment by duck** [comment]
sorry, I missed the reply.  I will try again over teh weekend and post it.

Thanks!

**Comment by pkgdemon** [comment]
No problem.  We have had some similar reports, and I believe we have resolved most of the issues with autodetection.  At this point we are releasing weekly snapshots.  If you get a chance try the image after 08-31-16, and let us know if you are still having issues.
