### ISSUE TITLE
PGP key?

### ISSUE THREAD

**Issue by reelsense** [trueos/trueos-desktop#4]
What is the PGP key for this project and where are the sig files for the releases? I would like to authenticate the image file on the TrueOS website.

Any help would be appreciated. Thank you!

**Comment by kmoore134** [comment]
The PGP key is now on the download page:

https://www.trueos.org/downloads/

ISO's (and the .sig files) are uploading now, should be on download.trueos.org in few hours.

**Comment by reelsense** [comment]
Thank you very much!
